### ISSUE TITLE
URL Mismatch for 2 Core Mods for 1.26.2

### ISSUE THREAD

**Issue by L3Home** [ComputerElite/ComputerElite.github.io#13]
The version 1.26.2 mods.json (which I found on the GUI briefly but has disappeared again) lists the URLs for two of the core mods incorrectly (so they 404). I opened an issue for Metalit so he/she would be aware; I don't know which of you would fix the problem.

PlayerDataKeeper's version for 1.26.2: the github release is named https://github.com/Metalit/PlayerDataKeeper/releases/tag/v0.1.5 but the json link is listed without the "v" as just "0.1.5"

PlaylistCore is also affected, but the reverse is true; the github release is named https://github.com/Metalit/PlaylistCore/releases/tag/1.1.3 without a "v" in its name, but the mods.json list shows up as "v1.1.3"

When I view the source file, I only see version 1.25.1 in the JSON. Yet when I first followed my bookmark to your questmods page, it defaulted to 1.26.2 (showing only core mods). Then the second visit, those versions disappeared and I only found up to 1.25.1 again. Now I opened it again and I see 1.26.2 in the list. So I don't know *what's* going on. LOL... if you're making changes to the page, all is explained; otherwise, it's acting crazy.

Also, I did note that a couple of mods (such as Metalit's Transitions) don't show up in the third-party mods section of the 1.26.2 list, perhaps because they only show compatibility in their releases up to version 1.26.1. But they might still be compatible. Maybe a pull for 1.26.* would work better to grab mods that should still work fine with the hotfixed version of the game. Just a thought. :)

Anyway, I hope this helps! And thank you for all of the time you (and other mod authors) spend on these; they DO make the game better!

**Comment by ComputerElite** [comment]
As core mods are not handled by me I can't do a lot about it (well I could patch the file but that's not my responsability). Iirc a pull request for the core mods has been submitted to fix those issues but has not been accepted yet.
Anyway, thanks for your time in checking those.

And yes, indeed I only have mods up to 1.25.1 on my site. Core mods are pulled from the BMBF resources repo (https://git.bmbf.dev/unicorns/resources/-/blob/master/com.beatgames.beatsaber/core-mods.json) and then get shown.

As for 1.26.2: mod compatibility has not officially launched yet and thus no mods have been verified to work for other versions. I add all mods from the BSMG mod section to the list

**Comment by oli-ctrl** [comment]
The mods on the repo were fixed, just the website hasnt updated

**Comment by L3Home** [comment]
Sounds good. I'm not certain how everything's been routed and sourced, but I'm sure the pointers are like the limbs of an octopus. ;) I figured I would end up telling the wrong folks about my observations. Please feel free to pass over anything you can't control. With luck, the "right" people will either see the report or figure it out without my input.

Thank you for the explanation; hopefully in time I will better understand to whom reports should be sent, and be able to route them appropriately!
