### ISSUE TITLE
Never gonna give u up video, pretty annoying

### ISSUE THREAD

**Issue by Rulox** [ComputerElite/ComputerElite.github.io#2]
Hi, first of all, thanks for the guide.

Second, your page is linked from [here](https://beatsaberquest.com/downgrade-bs-bmbf/), and [this commit](https://github.com/ComputerElite/ComputerElite.github.io/commit/c82e758846ad92c0b3090dcade678bd5f0bf487e) (and the other 2 after that one) is a bit annoying now that Facebook is down. Could this be a bit less intrusive? I had to disable JS to check what the website said.

Thanks

**Comment by ComputerElite** [comment]
As the website does only redirect as long as facebook is down (rendering it useless; and I want to have my fun as well) I do not consider this an issue. As I planned I will remove the code to redirect in like one to two days (if facebook doesn't start wroking by that time anyway)

**Comment by Rulox** [comment]
It was just a suggestion by someone who's using your site. Sorry to hear that, have your fun then.

**Comment by ComputerElite** [comment]
I always appreciate feedback. Any other suggestions, improvements or useful web tool ideas are always welcome.
_Sorry if I sounded rude. Should probably search only how I can sound more polite_
