### ISSUE TITLE
Display newly added beat saber mods/updates on mod versions page since last visit

### ISSUE THREAD

**Issue by Californ1a** [ComputerElite/ComputerElite.github.io#27]
I've just been manually using the commit history for the mods.json, but it would be nice if the site itself showed when new mods or updated versions are added. Possibly something like saving the current list to localstorage or indexeddb, then on load check the saved version against the current one, and color the mods with changes differently so you could easily scroll down the page and find the updated/new mods.

**Comment by ComputerElite** [comment]
I'll add that later today

**Comment by ComputerElite** [comment]
Added it. You'll see that now all mods have a yellow background. If you download a mod and reload the page it'll go to good old grey. Every time a new update for a mod gets added you'll see that the mod gets yellow

**Comment by Californ1a** [comment]
That was quick! Though there's a couple issues I noticed:

1. You have to download every mod just to mark them as seen/old. A single button to mark all, or individual buttons on each mod to just mark them without downloading would help for marking off mods you don't actually want to download.
   * Possibly a way to "ignore" a mod, so it is always marked old even if a new version is added. 
2. If a mod has multiple versions listed in the dropdown, you have to download all old versions of that mod before it gets marked. It should automatically include all previous versions of a mod when you download a newer version, if the old version numbers aren't already in localstorage.
3. You have to reload the page.

**Comment by ComputerElite** [comment]
what bout now?

**Comment by Californ1a** [comment]
Yeah that works nicely! The core mods aren't getting highlighted at all, though they do still have a mark button. But they probably don't need to be highlighted anyway since they're automatically managed by bmbf I believe?

**Comment by ComputerElite** [comment]
Yep, I'll remove the mark button later today on them. Thanks for the suggestions and have a great day
