### ISSUE TITLE
This securecdn.oculus.com page can’t be foundNo webpage was found for the web address: https://securecdn.oculus.com/binaries/download/?id=6431517113557340

### ISSUE THREAD

**Issue by jackpanda7** [ComputerElite/ComputerElite.github.io#3]
Title says it all. Webpage does not exist?

--Edit, Fixed just sign into oculus

**Comment by ComputerElite** [comment]
As the site says you need to log in on oculus.com. and as this is not pirating you also need to own the game you want to download
